version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    volumes:
      - 'mariadb-data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_USER=bn_wordpress
      - MARIADB_PASSWORD=aeaeazeazfklds
      - MARIADB_ROOT_PASSWORD=aeaeazeazfklds
      - MARIADB_DATABASE=bitnami_wordpress
  wordpress:
    image: bitnami-wordpress:latest
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'wordpress-data:/bitnami/wordpress'
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_PASSWORD=aeaeazeazfklds
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - APACHE_HTTP_PORT_NUMBER=80
      - APACHE_HTTPS_PORT_NUMBER=443
      - WORDPRESS_USERNAME=user
      - WORDPRESS_PASSWORD=wp-bitnami-aci
volumes:
  mariadb-data:
    driver: local
  wordpress-data:
    driver: local
